### ISSUE TITLE
XxlJobLogMapper.xml分页问题

### ISSUE THREAD

**Issue by tiaoxixiaoji** [Gigass/xxl-job-oracle#1]
pageList方法内的两行位置反了
) where r between #{offset}+1 and #{offset}+#{pagesize}
\<\/trim\>

**Comment by Gigass** [comment]
我看了下没问题哦

**Comment by tiaoxixiaoji** [comment]
如果if条件都不成立，sql会变成 
select *  from (
		SELECT row_number() over(ORDER BY t.trigger_time DESC) r,<include refid="Base_Column_List" />
		FROM xxl_job_log  t where 
) where r between #{offset}+1 and #{offset}+#{pagesize}

**Comment by Gigass** [comment]
变成这样有问题吗，应该也没问题吧

**Comment by Gigass** [comment]
bug fixed
