### ISSUE TITLE
xxl-job-admin修改端口静态资源加载错误

### ISSUE THREAD

**Issue by Roderick-zhang** [Gigass/xxl-job-oracle#3]
当我只修改xxl-job-admin的server.port=18088时，任务管理列表页面出现例如http://localhost:18088/xxl-job-admin/static/js/crongen.js net::ERR_ABORTED 404等静态资源加载报错，请问我应该怎么做？

**Comment by Gigass** [comment]
项目里面的是cornGen.js吧
![image](https://user-images.githubusercontent.com/37279049/103342281-1158a680-4ac4-11eb-8683-65d66421e22c.png)

**Comment by Roderick-zhang** [comment]
![image](https://user-images.githubusercontent.com/45482518/103342706-37cb1180-4ac5-11eb-8764-0e8163df39a2.png)

![image](https://user-images.githubusercontent.com/45482518/103342783-5e894800-4ac5-11eb-957a-5bba7bf3f435.png)

![image](https://user-images.githubusercontent.com/45482518/103342865-8ed0e680-4ac5-11eb-84f9-9d391b6ff5b8.png)

是的，页面加载出现一定的问题，我仅仅只是改了端口为18088，当我改回8088端口的时候就没有这些问题了，

**Comment by Gigass** [comment]
我在本机跑了改18088完全没有问题,如果你实在不行,你可以改前端代码去除cron表达式图形界面,直接把cron字符串复制进去就行

**Comment by Roderick-zhang** [comment]
找到原因了，Chrome缓存的原因导致我在改了端口之后找不到静态文件，清除缓存就好了

**Comment by Gigass** [comment]
解决了就好
